
#part part_name
head = Part.objects.create(part='head', part_name='머리')
top = Part.objects.create(part='top', part_name='상의')
bottom = Part.objects.create(part='bottom', part_name='하의')
foot = Part.objects.create(part='foot', part_name='발')
elsa = Part.objects.create(part='else', part_name='기타')

#cate1  cate1_name  part
long_outer = Cate1.objects.create(cate1='long_outer', cate1_name='긴 아우터', part=top)
short_outer	= Cate1.objects.create(cate1='short_outer', cate1_name='짧은 아우터', part=top)
suit_top = Cate1.objects.create(cate1='suit_top', cate1_name='정장 상의', part=top)
suit_bottom	= Cate1.objects.create(cate1='suit_bottom', cate1_name='정장 하의', part=bottom)
blazer = Cate1.objects.create(cate1='blazer', cate1_name='블레이저', part=top)
shirts = Cate1.objects.create(cate1='shirts', cate1_name='셔츠', part=top)
neat = Cate1.objects.create(cate1='neat', cate1_name='니트', part=top)
pants = Cate1.objects.create(cate1='pants', cate1_name='바지', part=bottom)
mantoman = Cate1.objects.create(cate1='mantoman', cate1_name='맨투맨', part=top)
hood = Cate1.objects.create(cate1='hood', cate1_name='후드', part=top)
tshirts	= Cate1.objects.create(cate1='tshirts', cate1_name=	'티셔츠', part=top)
sports_top = Cate1.objects.create(cate1='sports_top', cate1_name='트레이닝 상의', part=	top)
sports_bottom = Cate1.objects.create(cate1='sports_bottom', cate1_name=	'트레이닝 하의', part=bottom)
hat = Cate1.objects.create(cate1='hat', cate1_name=	'모자', part=head)
onepiece = Cate1.objects.create(cate1='onepiece', cate1_name='원피스', part=top)
skirt = Cate1.objects.create(cate1='skirt', cate1_name='치마', part=bottom)
shoe = Cate1.objects.create(cate1='shoe', cate1_name='신발', part=foot)
socks = Cate1.objects.create(cate1='socks', cate1_name='양말', part=foot)
accessory = Cate1.objects.create(cate1='accessory', cate1_name='액세서리', part=elsa)
bag	= Cate1.objects.create(cate1='bag', cate1_name=	'가방', part=elsa)

#cate2  cate2_name  cate1
coat = Cate2.objects.create(cate2='coat', cate2_name='코트', cate1=long_outer)
parka = Cate2.objects.create(cate2='parka', cate2_name='파카', cate1=long_outer)
trench = Cate2.objects.create(cate2='trench', cate2_name='트렌치 코트', cate1=long_outer)
l_padding = Cate2.objects.create(cate2='l_padding', cate2_name='롱패딩', cate1=long_outer)
s_padding = Cate2.objects.create(cate2='s_padding', cate2_name='숏패딩', cate1=short_outer)
leather = Cate2.objects.create(cate2='leather', cate2_name='가죽자켓', cate1=short_outer)
mustang = Cate2.objects.create(cate2='mustang', cate2_name='무스탕자켓', cate1=short_outer)
fleece = Cate2.objects.create(cate2='fleece', cate2_name='플리스', cate1=short_outer)
bomber = Cate2.objects.create(cate2='bomber', cate2_name='봄버자켓', cate1=short_outer)
denim = Cate2.objects.create(cate2='denim', cate2_name='데님자켓', cate1=short_outer)
vest = Cate2.objects.create(cate2='vest', cate2_name='조끼(베스트)', cate1=short_outer)
suit_t_daily = Cate2.objects.create(cate2='suit_t_daily', cate2_name='데일리 정장 상의', cate1=suit_top)
suit_t_evening = Cate2.objects.create(cate2='suit_t_evening', cate2_name='이브닝 정장 상의', cate1=suit_top)
suit_b_daily = Cate2.objects.create(cate2='suit_b_daily', cate2_name='데일리 정장 하의', cate1=suit_bottom)
suit_b_evening = Cate2.objects.create(cate2='suit_b_evening', cate2_name='이브닝 정장 하의', cate1=suit_bottom)
blazer_basic = Cate2.objects.create(cate2='blazer_basic', cate2_name='베이직 블레이저', cate1=blazer)
blazer_casual = Cate2.objects.create(cate2='blazer_casual', cate2_name='캐쥬얼 블레이저', cate1=blazer)
shirts_basic = Cate2.objects.create(cate2='shirts_basic', cate2_name='기본 셔츠', cate1=shirts)
shirts_formal = Cate2.objects.create(cate2='shirts_formal', cate2_name='정장 셔츠', cate1=shirts)
shirts_denim = Cate2.objects.create(cate2='shirts_denim', cate2_name='데님 셔츠', cate1=shirts)
shirts_blouse = Cate2.objects.create(cate2='shirts_blouse', cate2_name='블라우스', cate1=shirts)
shirts_corduroy = Cate2.objects.create(cate2='shirts_corduroy', cate2_name='코듀로이', cate1=shirts)
shirts_over = Cate2.objects.create(cate2='shirts_over', cate2_name='오버핏 셔츠', cate1=shirts)
shirts_half = Cate2.objects.create(cate2='shirts_half', cate2_name='반팔 셔츠', cate1=shirts)
shirts_else = Cate2.objects.create(cate2='shirts_else', cate2_name='기타', cate1=shirts)
neat_basic = Cate2.objects.create(cate2='neat_basic', cate2_name='니트 스웨터', cate1=neat)
neat_cardigan = Cate2.objects.create(cate2='neat_cardigan', cate2_name='가디건', cate1=neat)
neat_turtle = Cate2.objects.create(cate2='neat_turtle', cate2_name='터틀넥', cate1=neat)
pants_basic = Cate2.objects.create(cate2='pants_basic', cate2_name='면바지', cate1=pants)
pants_slacks = Cate2.objects.create(cate2='pants_slacks', cate2_name='슬랙스', cate1=pants)
pants_short = Cate2.objects.create(cate2='pants_short', cate2_name='반바지', cate1=pants)
pants_jean = Cate2.objects.create(cate2='pants_jean', cate2_name='진', cate1=pants)
pants_leggings = Cate2.objects.create(cate2='pants_leggings', cate2_name='레깅스', cate1=pants)
pants_else = Cate2.objects.create(cate2='pants_else', cate2_name='기타', cate1=pants)
mantoman_basic = Cate2.objects.create(cate2='mantoman_basic', cate2_name='기본 맨투맨', cate1=mantoman)
hood_jacket = Cate2.objects.create(cate2='hood_jacket', cate2_name='후드 집업', cate1=hood)
hood_basic = Cate2.objects.create(cate2='hood_basic', cate2_name='기본 후드', cate1=hood)
tshirts_basic = Cate2.objects.create(cate2='tshirts_basic', cate2_name='기본티', cate1=tshirts)
tshirts_long = Cate2.objects.create(cate2='tshirts_long', cate2_name='롱 슬리브', cate1=tshirts)
tshirts_polo = Cate2.objects.create(cate2='tshirts_polo', cate2_name='카라티', cate1=tshirts)
tshirts_sleeve = Cate2.objects.create(cate2='tshirts_sleeve', cate2_name='민소매', cate1=tshirts)
hat_baseball = Cate2.objects.create(cate2='hat_baseball', cate2_name='야구모자', cate1=hat)
hat_fedora = Cate2.objects.create(cate2='hat_fedora', cate2_name='페도라', cate1=hat)
hat_beanie = Cate2.objects.create(cate2='hat_beanie', cate2_name='비니', cate1=hat)
hat_beret = Cate2.objects.create(cate2='hat_beret', cate2_name='베렛', cate1=hat)
hat_snapback = Cate2.objects.create(cate2='hat_snapback', cate2_name='스냅백', cate1=hat)
hat_else = Cate2.objects.create(cate2='hat_else', cate2_name='기타', cate1=hat)
one_off = Cate2.objects.create(cate2='one_off', cate2_name='오프숄더', cate1=onepiece)
one_flower = Cate2.objects.create(cate2='one_flower', cate2_name='플라워 원피스', cate1=onepiece)
one_ethnic = Cate2.objects.create(cate2='one_ethnic', cate2_name='에스닉 원피스', cate1=onepiece)
one_sleeve = Cate2.objects.create(cate2='one_sleeve', cate2_name='슬리브리스', cate1=onepiece)
one_else = Cate2.objects.create(cate2='one_else', cate2_name='기타', cate1=onepiece)
skirt_minie = Cate2.objects.create(cate2='skirt_minie', cate2_name='미니', cate1=skirt)
skirt_midie = Cate2.objects.create(cate2='skirt_midie', cate2_name='미디', cate1=skirt)
skirt_long = Cate2.objects.create(cate2='skirt_long', cate2_name='롱스커트', cate1=skirt)
skirt_aline = Cate2.objects.create(cate2='skirt_aline', cate2_name='A라인', cate1=skirt)
skirt_hline = Cate2.objects.create(cate2='skirt_hline', cate2_name='H라인', cate1=skirt)
skirt_flared = Cate2.objects.create(cate2='skirt_flared', cate2_name='플레어', cate1=skirt)
skirt_else = Cate2.objects.create(cate2='skirt_else', cate2_name='기타', cate1=skirt)
shoe_sports = Cate2.objects.create(cate2='shoe_sports', cate2_name='운동화', cate1=shoe)
shoe_boots = Cate2.objects.create(cate2='shoe_boots', cate2_name='부츠', cate1=shoe)
shoe_heel = Cate2.objects.create(cate2='shoe_heel', cate2_name='힐', cate1=shoe)
shoe_sneakers = Cate2.objects.create(cate2='shoe_sneakers', cate2_name='스니커즈', cate1=shoe)
shoe_sandal = Cate2.objects.create(cate2='shoe_sandal', cate2_name='샌들', cate1=shoe)
shoe_flat = Cate2.objects.create(cate2='shoe_flat', cate2_name='플랫 슈즈', cate1=shoe)
shoe_loafer = Cate2.objects.create(cate2='shoe_loafer', cate2_name='로퍼', cate1=shoe)
shoe_else = Cate2.objects.create(cate2='shoe_else', cate2_name='기타', cate1=shoe)
socks_basic = Cate2.objects.create(cate2='socks_basic', cate2_name='기본 양말', cate1=socks)
socks_ankle = Cate2.objects.create(cate2='socks_ankle', cate2_name='발목 양말', cate1=socks)
socks_knee = Cate2.objects.create(cate2='socks_knee', cate2_name='니삭스', cate1=socks)
acc_earings = Cate2.objects.create(cate2='acc_earings', cate2_name='귀걸이', cate1=accessory)
acc_ring = Cate2.objects.create(cate2='acc_ring', cate2_name='반지', cate1=accessory)
acc_bracelet = Cate2.objects.create(cate2='acc_bracelet', cate2_name='팔찌', cate1=accessory)
acc_watch = Cate2.objects.create(cate2='acc_watch', cate2_name='시계', cate1=accessory)
bag_backpack = Cate2.objects.create(cate2='bag_backpack', cate2_name='백팩', cate1=bag)
bag_cross = Cate2.objects.create(cate2='bag_cross', cate2_name='크로스백', cate1=bag)
bag_echo = Cate2.objects.create(cate2='bag_echo', cate2_name='에코백', cate1=bag)
bag_else = Cate2.objects.create(cate2='bag_else', cate2_name='기타', cate1=bag)
sports_top_basic = Cate2.objects.create(cate2='sports_top_basic', cate2_name='기본', cate1=sports_top)
sports_bottom_basic = Cate2.objects.create(cate2='sports_bottom_basic', cate2_name='기본', cate1=sports_bottom)
